### ISSUE TITLE
Provide a way to get download status

### ISSUE THREAD

**Issue by bczsalba** [tHoMaStHeThErMoNuClEaRbOmB/teahaz-server#2]
This would be useful for progress indication, as the current method isn't too sophisticated. 

It could be with a separate request, or it could be returned as a field on the first request. It could be detected, since it has `{'fileId': null}`.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
I am currently re-writing how files are handled, and I have added a way for you to keep track of this. Ik its not what you asked precisely, but I added a file-size filed to the messages object, which should let you calculate progress easily. 

This will be especially simple because the filesize is measured in chunks! :slightly_smiling_face:

**Comment by bczsalba** [comment]
Chunk based representation is exactly what I was hoping for, so thank you!

For now I need to finish implementing teahaz.py into the client, and then I'll add all your cool file changes!
🚀

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
It might be a while till its done, as Im on a small break rn. Ill either have some time tomorrow or just on wednesday, either way the feature should be ready by the end of the week.
