### ISSUE TITLE
Add `/messages/` `GET` by time

### ISSUE THREAD

**Issue by bczsalba** [tHoMaStHeThErMoNuClEaRbOmB/teahaz-server#3]
This would allow clients checking messages in a neater way.

With only being able to get `count` messages, a client would have to get some messages in a loop, and break out once it finds something it's already seen. This is needlessly complex, and is really inefficient.

`count` GET should still remain however, since getting initial messages should not be done by time, as it's really resource-greedy.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Great Idea, I  just finished implementing it!


Requests now have to have a `get-method` parameter which can be set to `since` or `count`. (alternatively 0 or 1 do the same thing) . Requests sent with `get-method: since` need a `time` parameter that specifies the epoch time of when you last got messages. The server should return all messages since then. 
`get-method: count` is exactly the same as get was before this update 

**However**  there are some issues with `get-method: since`. Due to performance issues it is limited to maximum 100 messages and has no way of telling you that some messages have been skipped. This is due to the sqlite handling the limit of 100, and the  fact that getting all the messages and filtering would be a bigger performance hit then just returning all messages the user asked for. For this reason I dont think this should be a public method on the client-program as it could lead to a lot of headaches when messages are missing, but rather a way to make a get loop that isnt stupid.

**Comment by bczsalba** [comment]
> Due to performance issues it is limited to maximum 100 messages

Could this be enforced by the server? Just so people don't try and report it as not working.

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Well the server has no idea how many messages have been sent in that time. This will be a documented issue with the function, but I dont really see any way I can fix or warn the user without a serious performance hit.

**Comment by bczsalba** [comment]
> Well the server has no idea how many messages have been sent in that time. This will be a documented issue with the function, but I dont really see any way I can fix or warn the user without a serious performance hit.

Ohh, yeah that's fair.
