### ISSUE TITLE
Potentially revert `userID` system to separate `username` and `nickname`

### ISSUE THREAD

**Issue by bczsalba** [tHoMaStHeThErMoNuClEaRbOmB/teahaz-server#5]
The current system is nice on a backend level, but is really hard to use as a user. In order to log in, the user would have to remember their `userID`, which is a random `UUID`, different to every chatroom. (Obviously, some of these issues would be solved by `Teapass`, but it needs to be optional only)

The proposed change would change `userID` to `username`, in that it is a per-chatroom unique identifier of a user, and add the new field `nickname`. `nickname` would initially mirror `username`, but would be user-settable to any value (within limits). The `username` should only be displayed in user-information menus, while `nickname` should be used everywhere else.

Example data:
```python3
{
    "username": "alma",
    "nickname": "[157]alma [:apple:]"
}
```

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
This Idea makes sense and I will get to work on it soon.

I dont know all the details of how the improved system will work until I get to implementing it as thats when hiccups usually come up, but I will probably implement one of the following ideas.

1. Revert back to username and nickname fully. In this case username will never be changable and we will have to bring back a nickname field. 
     
This method might have some performance or security issues in the form of injection attacks, but im not sure until I take a closer look into it. Might end up with some sort of encoded or hashed value of the username, which could probably have some amount of performance penalty.

- userID still exists but it is only internal.

In this case the server will have some sort of lookup table (database) for all usernames and their corresponding userIDs and allow users to log in with that username. Obviously this would mean that usernames have to be unique. 


Hope I can get to it soon :slightly_smiling_face:

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
Done!
We have fully reverted back to username and nickname.  For the most part you can just use these as you used userID and nickname previously with some small minor changes:

- You obviously have to supply a username when registering because its not auto generated on the server
- You can optionally supply a nickname, if not then it will be the same as the username

As of now nicknames cannot be changed, but that will come later.

**NOTE**: This is a pretty big change that affected a huge percentage of the code of the server so there will probably be bugs caused by it. I have tried to iron out what I can but if you find something feel free to re-open this issue. :slightly_smiling_face:

**Comment by tHoMaStHeThErMoNuClEaRbOmB** [comment]
P.S docs have not yet been updated but most of it should be pretty obvious.
